kind: pipeline
type: docker
name: Create Release

trigger:
  event:
    - push
  branch:
    - main
  tag:
    - 'v*'

platform:
  os: linux
  arch: amd64

steps:
  - name: Checkout
    image: plugins/git
    settings:
      depth: 1

  - name: Build Firmware
    image: ubuntu:20.04
    commands:
      - apt-get update
      - apt-get install -y device-tree-compiler g++ ncurses-dev python asciidoc bash bc binutils bzip2 fastjar flex gawk gcc genisoimage gettext git intltool jikespg libgtk2.0-dev libncurses5-dev libssl-dev make mercurial patch perl-modules python2.7-dev rsync ruby sdcc subversion unzip util-linux wget xsltproc zlib1g-dev
      - chmod +x buildbot.sh
      - ./buildbot.sh
